apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: ai-task-platform

type: Opaque

stringData:
  MONGO_URI: "mongodb+srv://tanvik:tanzai@aitask.cjgyhxd.mongodb.net/?appName=Aitask"
  JWT_SECRET: "mySuperSecretKey123"