name: AI Task Platform CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --------------------
      # Backend
      # --------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci

      # --------------------
      # Frontend
      # --------------------
      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm ci

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      # --------------------
      # Worker
      # --------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Worker Dependencies
        working-directory: worker
        run: pip install -r requirements.txt

      # --------------------
      # Docker Login
      # --------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --------------------
      # Backend Image
      # --------------------
      - name: Build Backend Image
        run: docker build -t tanvi005/ai-task-platform-backend:latest ./backend

      - name: Push Backend Image
        run: docker push tanvi005/ai-task-platform-backend:latest

      # --------------------
      # Frontend Image
      # --------------------
      - name: Build Frontend Image
        run: docker build -t tanvi005/ai-task-platform-frontend:latest ./frontend

      - name: Push Frontend Image
        run: docker push tanvi005/ai-task-platform-frontend:latest

      # --------------------
      # Worker Image
      # --------------------
      - name: Build Worker Image
        run: docker build -t tanvi005/ai-task-platform-worker:latest ./worker

      - name: Push Worker Image
        run: docker push tanvi005/ai-task-platform-worker:latest